deployment:

  containers:
    image: jdvincent/ml-image-to-tensor-s3-app:latest
  
  envVars:
    ARGO_SERVER_HOST: my-argo-workflows-server.argo
    ARGO_SERVER_PORT: "2746"
    ARGO_TOKEN: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IlRiNmdTb3Naa04xTk5tbm1EcFZEeU5KLVlua0toNFhPM1NyczVveDcyOEkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJhcmdvIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImFwcC5zZXJ2aWNlLWFjY291bnQtdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiYXBwIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiNDVhZjcyNjctZmMxNy00YzVkLWEwM2MtNTVlZWQwYWZlMWI0Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmFyZ286YXBwIn0.Shx9VG-A-d_RdY1NY71SzAuGGsFoQfWl0nXcLlYHBPpI6taYNSlFvyZMi-NV2aXAdhRwaDBosA4dwormiX71cILH5WgiSLPQvJdV3dqHC2cufNeYAlaF31t0WzH7BkT1lKmuQx_OCNjfsrFZzECPijTEO8W_Dw2mIdpemod7y_GXXgq4XN4Z93K8Le4F1KEr9JBNZ6KolBJ0XFXVgh8hbPWt4VPujJQvnH9vmdU64WxCYS3g5qjuthzJHLd3Gzl0CUz-kkCxFphFsvFmu83waiTbn2PIJwJrGoNbi36Dzz8eF1DHi-HR4dNNVb_n_ROQ64ik5rArK8_5ffZumSpvAw
    S3_NAME: argo-workflows-velocity
