cronJob:
  annotations:
    velocity.tech.v1/id: "argo-ml-pipeline"
    velocity.tech.v1/dependsOn: bucket

  containers:
    image: jdvincent/ml-image-to-tensor-s3-job:latest
  
  envVars:
    ARGO_SERVER_HOST: my-argo-workflows-server.argo
    ARGO_SERVER_PORT: "2746"
    ARGO_TOKEN: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IlRDSE1hTThXeXBvSUFRbl9aQXF4ZU9ybmpkRVdFMTRVNEtqMl9ZYVdURmMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJhcmdvIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImFwcC5zZXJ2aWNlLWFjY291bnQtdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiYXBwIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZTdhZDAzNTgtYzc5MS00Mzk4LTk0ODgtY2Y1MmY1NzVjMDFjIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmFyZ286YXBwIn0.kBrQB7FJLVYBo3yVvGMMAr1fRToKhLQA-PFVTB_ss5pUqT8Ar9NHAn-05B6iMV0p-XqYKcjF0KfXmyL2K8WqDzMlDKMxOpjxJQQYc-cFfsHjlBw7Z1Q-nXqAsGFyYcMUVoWhaysngwmolRg02O_NBQn0pzXXWkjKQPBLDIt38AXNFecriCm9HaMrKgvFLD70m0s3jxsNvRwjSN-buw194_1Da4a3SjS70MeNkDW6jwxWI6xwl8xpbCBhgLm0O-Qtol1jZ8yZflgzGxnStG3DOdvkrc4PcvZcJyFgWVNbsEE0O4V_27V4NzmWhXrfnXstZrOiR71tjGvp_88e5lgbUQ
    S3_NAME: "{velocity.v1:bucket.exports.path}"

S3:
  annotations:
    velocity.tech.v1/exports-path: path="spec.name"
    velocity.tech.v1/id: bucket
  name: "{velocity.v1.generate:cloudResourcePrefix}-my-bucket"
