apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: prep-images-
spec:
  ttlStrategy:
    secondsAfterCompletion: 10
  entrypoint: prep-images
  templates:
  - name: prep-images
    container:
      image: jdvincent/ml-image-to-tensor-s3-workflow:latest
      imagePullPolicy: IfNotPresent
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_secret_access_key
        - name: AWS_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_session_token
        - name: S3_NAME
          value: argo-workflows-velocity
